# Generated by Django 4.2.24 on 2026-09-24

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Main_Img',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
    ]