# Generated by Django 4.2.24 on 2026-09-24

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_harden_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description_video',
            field=models.FileField(blank=True, null=True, upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
    ]