# Generated by Django 4.2.24 on 2026-09-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_userprofile_tenantprofile_landlordprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='is_test_data',
            field=models.BooleanField(default=False, help_text='Marks this listing as demo/test data for QA.'),
        ),
    ]
