# Generated by Django 4.2.24 on 2026-09-24 16:08

import django.core.validators
from django.db import migrations, models
import products.models
import products.storage


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_description_is_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description_video_2',
            field=models.FileField(blank=True, null=True, storage=products.storage.PropertyVideoStorage(), upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AddField(
            model_name='description',
            name='description_video_3',
            field=models.FileField(blank=True, null=True, storage=products.storage.PropertyVideoStorage(), upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_5',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_6',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_7',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_8',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AddField(
            model_name='description',
            name='image_9',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_video',
            field=models.FileField(blank=True, null=True, storage=products.storage.PropertyVideoStorage(), upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_1',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_2',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_3',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_4',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=products.storage.PropertyImageStorage(), upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
    ]
