# Generated by Django 4.2.24 on 2026-09-24 16:42

import django.core.validators
from django.db import migrations, models
import products.models
import products.storage


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_description_description_video_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description_video_4',
            field=models.FileField(blank=True, null=True, storage=products.storage.PropertyVideoStorage(), upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AddField(
            model_name='description',
            name='description_video_5',
            field=models.FileField(blank=True, null=True, storage=products.storage.PropertyVideoStorage(), upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
    ]
