# Generated by Django 4.2.24 on 2026-09-24 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_description_description_video_4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInterestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=120)),
                ('salary_range', models.CharField(max_length=80)),
                ('employer', models.CharField(blank=True, max_length=160)),
                ('occupants_count', models.PositiveIntegerField(default=1)),
                ('lease_start_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_interest_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_requests', to='products.description')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
