# Generated by Django 4.2.24 on 2026-09-25 15:50

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_propertyinterestmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_video_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_video_3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_video_4',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_video_5',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=products.models.property_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), products.models.validate_property_video]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_5',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_6',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_7',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_8',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_9',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='main_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.models.property_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='description',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='descriptions/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Main_Img',
            field=models.ImageField(max_length=255, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=products.models.property_document_upload_path),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=products.models.property_media_upload_path),
        ),
    ]
