# Generated by Django 4.2.24 on 2026-09-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_file_fields_max_length_255'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='rental_type',
            field=models.CharField(choices=[('long_term', 'Long term (monthly rent)'), ('short_term', 'Short term (per night / week)')], db_index=True, default='long_term', max_length=20),
        ),
        migrations.AddField(
            model_name='description',
            name='weekly_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
